#!/bin/bash

echo 'Iniciado'
apt-get update 

apt-get upgrade -y
echo"atualizando"

apt-get install apache2 -y
echo"instalando apache2"
apt-get install unzip -y

cd /tmp/

wget https://github.com/denilsonbonatti/linux-site-dio/archive/refs/heads/main.zip

unzip  main.zip
echo"extraindo pasta"
cd linux-site-dio-main
cp -R * /var/www/html
